import type { VideoFeatures } from '../schema.ts';
import type { SampledFrame } from '../preprocess.ts';

/**
 * The seam between frame sampling and whatever produces taxonomy features.
 *
 * Deliberately says nothing about HTTP, OpenAI message formats, base64 images or
 * token budgets. A provider receives sampled frames and returns validated
 * features; how it gets there is its own business. That keeps a self-hosted
 * server, a hosted API, a local ONNX model and the deterministic mock all
 * interchangeable behind one contract - which is what makes the model a
 * benchmarking decision rather than an architectural commitment.
 */

export interface VideoAnalysisInput {
  videoId: string;
  durationSeconds: number;
  /** Chronological, already de-duplicated. Frames exist on disk for this call only. */
  frames: readonly SampledFrame[];
}

export interface VisionUsage {
  tokensIn: number | null;
  tokensOut: number | null;
}

export interface VisionAnalysis {
  features: VideoFeatures;
  /** Unparsed provider response, kept for debugging and re-encoding. */
  raw: unknown;
  modelName: string;
  modelVersion: string;
  promptVersion: number;
  usage: VisionUsage;
  latencyMs: number;
  /** How many model calls it took, including schema-repair retries. */
  attempts: number;
}

export interface VisionProvider {
  /** Adapter identity, e.g. "mock" or "openai-compatible". */
  readonly name: string;
  /** Model identity, stored per row so results stay attributable. */
  readonly modelName: string;
  readonly modelVersion: string;
  /**
   * True when output is fabricated rather than derived from the video.
   *
   * Every surface that shows features to a human - CLI, reports, demo UI - must
   * check this and say so. Synthetic tags that look like analysis are worse than
   * no tags: they invite conclusions about a corpus that nothing ever looked at.
   */
  readonly synthetic: boolean;
  analyze(input: VideoAnalysisInput): Promise<VisionAnalysis>;
}

/** How a provider failed, so logs and reports can group causes. */
export type VisionErrorKind =
  | 'transport'
  | 'timeout'
  | 'invalid_json'
  | 'schema_validation'
  | 'model_error'
  | 'no_frames';

/** Raised when a provider cannot produce schema-valid output. */
export class VisionError extends Error {
  constructor(
    message: string,
    readonly kind: VisionErrorKind,
    readonly attempts: number,
    options?: { cause?: unknown },
  ) {
    super(message, options);
    this.name = 'VisionError';
  }
}

/** Banner shown wherever synthetic features could be mistaken for real analysis. */
export const SYNTHETIC_WARNING =
  'SYNTHETIC FEATURES - generated by the mock provider, not derived from video content. ' +
  'Dev/test only; not a description of the corpus.';
